PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
CREATE TABLE STUDENTS(
ROLL_NO INT NOT NULL,
NAME TEXT NOT NULL,
DEPT TEXT,
PRIMARY KEY(ROLL_NO));
CREATE TABLE FACULTY(
FACULTY_ID INT NOT NULL,
FACULTY_NAME TEXT,
PRIMARY KEY(FACULTY_ID));
CREATE TABLE COURSES(
COURSE_ID INT NOT NULL,
COURSE_NAME TEXT NOT NULL,
FACULTY_ID INT NOT NULL,
CREDITS INT,
PRIMARY KEY(COURSE_ID),
FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY(FACULTY_ID));
CREATE TABLE ENROLLMENT(
ROLL_NO INT NOT NULL,
COURSE_ID NOT NULL,
ASSIGNMENT_MARKS INT,
QUIZ_MARKS INT,
MIDSEM_MARKS INT,
ENDSEM_MARKS INT,
TOTAL INT,
GRADE TEXT,
FOREIGN KEY (ROLL_NO) REFERENCES STUDENTS(ROLL_NO),
FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID));
COMMIT;
